services:
  - type: web
    name: first-app
    env: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm ci
      npm run build
      php artisan storage:link || true
    preDeployCommand: |
      php artisan migrate --force
      php artisan db:seed --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: DATABASE_URL
        fromDatabase:
          name: first-app-db
          property: connectionString
      - key: APP_KEY
        value: "base64:pk2Bj4PGw4dG4Lhv0HyyuyWbnGoMstiZmgsIzZIxvBo="
        sync: false

databases:
  - name: first-app-db
    plan: starter